// Generated from docs/schemas/pp-possible-values.md; edit the Markdown source instead.
export const PATIENT_PROFILE_HISTORY_SECTIONS = [
  "Symptoms and menstrual history",
  "Medical, gynecologic, medication, and allergy history",
  "Other treatments and procedures",
  "Pregnancy and reproductive history",
  "Menopause-related history",
  "Sexual health and relationships",
  "Family, substance use, and daily life",
  "Safety, trauma, and other information"
] as const
export const PATIENT_PROFILE_FIELD_SECTIONS = {
  "lastMenstrualPeriod": "Symptoms and menstrual history",
  "typicalMenstrualPeriodDescription": "Symptoms and menstrual history",
  "dysmenorrheaHistory": "Symptoms and menstrual history",
  "anyPain": "Symptoms and menstrual history",
  "whatProvokesPalliatesPain": "Symptoms and menstrual history",
  "painQuality": "Symptoms and menstrual history",
  "painLocationRadiationWhere": "Symptoms and menstrual history",
  "painSeverity0-10": "Symptoms and menstrual history",
  "timePainOnset": "Symptoms and menstrual history",
  "constantIntermittentPain": "Symptoms and menstrual history",
  "durationPain": "Symptoms and menstrual history",
  "patientConcern": "Symptoms and menstrual history",
  "medicalHistory": "Medical, gynecologic, medication, and allergy history",
  "lastPelvicExam": "Medical, gynecologic, medication, and allergy history",
  "lastPapSmear": "Medical, gynecologic, medication, and allergy history",
  "lastBreastExam": "Medical, gynecologic, medication, and allergy history",
  "lastMammogram": "Medical, gynecologic, medication, and allergy history",
  "comorbidity": "Medical, gynecologic, medication, and allergy history",
  "currentMedications": "Medical, gynecologic, medication, and allergy history",
  "allergies": "Medical, gynecologic, medication, and allergy history",
  "pastMedications": "Medical, gynecologic, medication, and allergy history",
  "nutraceuticalUse": "Medical, gynecologic, medication, and allergy history",
  "supplementVitaminUse": "Medical, gynecologic, medication, and allergy history",
  "tradChineseMedicine": "Other treatments and procedures",
  "homeopathicTreatmentsMeds": "Other treatments and procedures",
  "acupunctureHistory": "Other treatments and procedures",
  "surgicalHistory": "Other treatments and procedures",
  "obstetricalHistory": "Pregnancy and reproductive history",
  "numberPregnancies": "Pregnancy and reproductive history",
  "numberMiscarriage": "Pregnancy and reproductive history",
  "numberStillbirths": "Pregnancy and reproductive history",
  "numberAbortions": "Pregnancy and reproductive history",
  "numberEctopicPregnancies": "Pregnancy and reproductive history",
  "numberLiveBirths": "Pregnancy and reproductive history",
  "numberChildren": "Pregnancy and reproductive history",
  "tubalLigation": "Pregnancy and reproductive history",
  "hysterectomyHistory": "Pregnancy and reproductive history",
  "perimenopauseStatus": "Menopause-related history",
  "perimenopauseSymptoms": "Menopause-related history",
  "menopauseStatus": "Menopause-related history",
  "menopauseSymptoms": "Menopause-related history",
  "postmenopauseStatus": "Menopause-related history",
  "postmenopauseSymptoms": "Menopause-related history",
  "hormoneReplacementTherapy": "Menopause-related history",
  "sexualActivityCurrent": "Sexual health and relationships",
  "contraceptionMethods": "Sexual health and relationships",
  "stdHistory": "Sexual health and relationships",
  "relationshipStatus": "Sexual health and relationships",
  "familyMedicalHistory": "Family, substance use, and daily life",
  "illicitDrugUse": "Family, substance use, and daily life",
  "cannabisUse": "Family, substance use, and daily life",
  "methadoneTreatment": "Family, substance use, and daily life",
  "alcoholUse": "Family, substance use, and daily life",
  "nutritionHabits": "Family, substance use, and daily life",
  "sleepQualityQuantity": "Family, substance use, and daily life",
  "mentalHealthCurrent": "Family, substance use, and daily life",
  "mentalHealthPast": "Family, substance use, and daily life",
  "homeEnvironment": "Family, substance use, and daily life",
  "lifeStyle": "Family, substance use, and daily life",
  "employmentHistory": "Family, substance use, and daily life",
  "educationalHistory": "Family, substance use, and daily life",
  "exerciseCurrent": "Family, substance use, and daily life",
  "mentalAbuseHistory": "Safety, trauma, and other information",
  "physicalAbuseHistory": "Safety, trauma, and other information",
  "sexualAbuseHistory": "Safety, trauma, and other information",
  "dnaStudies": "Safety, trauma, and other information",
  "miscellaneousDetailsNos": "Safety, trauma, and other information"
} as const
